### ISSUE TITLE
ADFS integration Error: The requested relying party trust is unspecified or unsupported

### ISSUE THREAD

**Issue by Airtonmartins** [fangli/django-saml2-auth#148]
Hi, I'm trying to integrate our application with ADFS Authentication from a client, I followed the settings in documentation, when try login I receive an error in ADFS log:

```
Protocol Name: 
Saml 

Relying Party: 
https://MY_DOMAIN/saml2_auth/acs/ 

Exception details: 
Microsoft.IdentityServer.Web.InvalidScopeException: MSIS7007: The requested relying party trust 'https://MY_DOMAIN/saml2_auth/acs/' is unspecified or unsupported. If a relying party trust was specified, it is possible that you do not have permission to access the trust relying party. Contact your administrator for details.
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlSignInContext.ValidateCore()
   at Microsoft.IdentityServer.Web.Protocols.ProtocolContext.Validate()
   at Microsoft.IdentityServer.Web.Protocols.Saml.SamlProtocolHandler.GetRequiredPipelineBehaviors(ProtocolContext pContext)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.EvaluateHomeRealm(PassiveProtocolHandler protocolHandler, ProtocolContext protocolContext)
   at Microsoft.IdentityServer.Web.PassiveProtocolListener.OnGetContext(WrappedHttpListenerContext context)
```

My settings:

```
SAML2_AUTH = {
    'METADATA_AUTO_CONF_URL': https://CLIENT_DOMAIN/FederationMetadata.xml,
    'CREATE_USER': 'TRUE',
    'NEW_USER_PROFILE': {
        'USER_GROUPS': [],  
        'ACTIVE_STATUS': True,  
        'STAFF_STATUS': True,  
        'SUPERUSER_STATUS': True,  
    },
    'ATTRIBUTES_MAP': {  attributes.
        'email': '...claims/email',
        'first_name': '...claims/name',
    },
    'ASSERTION_URL': MY_DOMAIN,
    'ENTITY_ID': .../saml2_auth/acs/,
    'USE_JWT': True,
    'FRONTEND_URL': MY_DOMAIN',  
    'NAME_ID_FORMAT': 'None',
}
```

ADFS server settings:

Relying party identifiers: 
MY_DOMAIN
https://MY_DOMAIN

Endpoints:
SAML Assertion Consumer endpoints: https://MY_DOMAIN/saml2_auth/acs/

**Comment by joreize** [comment]
Hello Airtonmartins,

did you find a solution for your problem?
I'm having the same issue while implementing DefectDojo and SAML.

Best Regards
Johannes
